// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Dashboard__AccountsController from "./dashboard/accounts_controller"
application.register("dashboard--accounts", Dashboard__AccountsController)

import Dashboard__PostsController from "./dashboard/posts_controller"
application.register("dashboard--posts", Dashboard__PostsController)

import DashboardTagsController from "./dashboard_tags_controller"
application.register("dashboard-tags", DashboardTagsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import PostFormController from "./post_form_controller"
application.register("post-form", PostFormController)

import PostsController from "./posts_controller"
application.register("posts", PostsController)

import ShareController from "./share_controller"
application.register("share", ShareController)
