// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DashboardTagsController from "./dashboard_tags_controller"
application.register("dashboard-tags", DashboardTagsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
